import React from "react";

function Head() {
  return (
    <>
      <title>Ebru</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" sizes="any" />
    </>
  );
}

export default Head;
